criteo/autofaiss

- autofaiss/datasets/readers/local_iterators.py
- autofaiss/external/build.py
- autofaiss/external/optimize.py
- autofaiss/external/quantize.py
- autofaiss/external/scores.py
- autofaiss/indices/memory_efficient_flat_index.py
- tests/unit/test_local_iterators.py
There were 2 issues:
* using np.concatenate means using x2 the memory (especially an issue when we do 1 big batch for training)
* the float32 conversion was doing x2 the memory
The solution adopted is to:
* remove the stack input parameter and replace it by a batch size one
* use this known in advance batch size to pre allocate a np array of that size
* loop over files to fill up this np array, yield when batch size is reached
* load files as memory mapped to avoid doing a x2 when converting to float32
This solves the 2 issues:
* the memory is now capped at batch_size * dim * 4, with no spike above that possible
* if reading float16 embeddings (for example output of clip), no copy is necessary thanks to np load with memory mapping
> Make the local numpy iterator memory efficient

- autofaiss/readers/embeddings_iterators.py
readline is not supported by pyarrow
I'm not sure how this worked before
> fix shape reading for numpy format

- autofaiss/readers/embeddings_iterators.py
it was already working because it overwrote the content of the previous batch, but this is safer
> clean ids_batch and ids_batch_df between each batch

- autofaiss/readers/embeddings_iterators.py
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-2a3c85a29b16> in <module>()
13     knn_extra_neighbors = 10,                     # num extra neighbors to fetch
14     max_index_memory_usage = '1m',
---> 15     current_memory_available = '1G'
16 )
7 frames
/usr/local/lib/python3.7/dist-packages/retro_pytorch/training.py in __init__(self, retro, chunk_size, documents_path, knn, glob, chunks_memmap_path, seqs_memmap_path, doc_ids_memmap_path, max_chunks, max_seqs, max_docs, knn_extra_neighbors, **index_kwargs)
160             num_nearest_neighbors = knn,
161             num_extra_neighbors = knn_extra_neighbors,
--> 162             **index_kwargs
163         )
164 …
```
> Fix "ValueError: substring not found" on line 201

- autofaiss/indices/distributed.py
This PR should fix the problem on id mismatching. Ids is mismatched because merging order is wrong.
> Fix the order of indices when merging

- autofaiss/external/build.py
- autofaiss/external/metadata.py
This fix training and memory estimation by over estimating training memory a bit (x1.5 of the training vectors)
That prevents OOM but is not optimal
A proper fix can be tracked at https://github.com/criteo/autofaiss/issues/85
> fix training memory estimation

- autofaiss/indices/distributed.py
> save temporary indices directly to the specified temporary folder

- autofaiss/indices/distributed.py
this was causing an issue when merging
for example if nb_indices_on_src_folder = 554 and n = 100
then batch_size = 6
which means that _batch_loader will generate one batch from 594 and 600 which will be empty and result in crash
> fix the number of batches in merge n indices

- autofaiss/external/optimize.py
- autofaiss/external/quantize.py
- autofaiss/external/scores.py
- autofaiss/indices/distributed.py
- autofaiss/indices/index_utils.py
- autofaiss/utils/path.py
* use_listings_cache=False to avoid caching the file listings which is an issue on some fs (eg s3)
*  fsspec.open -> fs.open
* use multiple subfolder in temp folder in order to avoid confusing when listing files in it
> fixes to n indices merging and optimizing

- autofaiss/indices/distributed.py
minor fix at the end of the job
needed on s3 because the concept of folder doesn't actually exist
so removing all the files in a folder (done in _merge_index) already removed the folder
> check if folder exists before removing

- autofaiss/external/quantize.py
- autofaiss/indices/distributed.py
- examples/distributed_autofaiss_n_indices.py
- requirements.txt
- tests/unit/test_quantize.py
this makes it possible to use faiss.merge_ondisk (https://github.com/facebookresearch/faiss/blob/30abcd6a865afef7cf86df7e8b839a41b5161505/contrib/ondisk.py )
https://github.com/facebookresearch/faiss/blob/151e3d7be54aec844b6328dc3e7dd0b83fcfa5bc/demos/demo_ondisk_ivf.py
to merge indices on disk without using memory, and then use a very large index with almost no memory usage.
required if the number of indices piece makes the overhead (around 500MB) of loading memmaped indices too large.
example of merge on disk usage that is made possible after this pr:
```python
from faiss.contrib.ondisk import merge_ondisk
import faiss
block_fnames = [ "index_%03d" % i for i in range(10)]
empty_index = faiss.read_index(block_fnames[0], faiss.IO_FLAG_MMAP)
empty_index.ntotal = 0
merge_ondisk(empty_index, …
```
> use index.add_with_ids to have consecutive ids in N indices mode

- autofaiss/indices/index_utils.py
The temporary file under /tmp/ could be deleted before it is used, using NamedTemporaryFile is more safe.
> Fix get_index_size by using NamedTemporaryFile

- examples/distributed_autofaiss_n_indices.py
the populated index should use faiss.IO_FLAG_ONDISK_SAME_DIR because it points to merged_index.ivfdata
however it doesn't make sense to use faiss.IO_FLAG_MMAP for it, as the ivf inverted lists are already using the on disk implementation
> fix how to read populated.index in distributed_autofaiss_n_indices

- autofaiss/external/quantize.py
It would save aound 20% disk usage.
> Do not save dataframe index for ids

- autofaiss/indices/distributed.py
- tests/unit/test_distirubted.py
When `nb_indices_on_src_folder` = 101 and `n` (`nb_nbindices_to_keep`) =10,
it generated 11 output files instead of 10.
Now it can generate 10 outputs.
> Fix the number of output index files

- autofaiss/external/build.py
- autofaiss/indices/distributed.py
- tests/unit/test_distirubted.py
In the last [PR](https://github.com/criteo/autofaiss/pull/119), we could have empty batch. There was an error in the unit test, so we didn't find the bug.
To fix it, this PR refactors the function `_batch_loader`, now it outputs exactly the number of batches we expect (in the case where total size is bigger than or equal to the expected number of batches).
The unit test has been improved as well.
> Fix "Fix the number of output index files (#119)"

- autofaiss/indices/distributed.py
- autofaiss/indices/training.py
- autofaiss/utils/cast.py
These methods now:
- Accept a final output directory instead of inferring one.
- Accept multiple input embedding directories instead of only one.
> Improve methods to create small and big indexes for more flexibility

- CHANGELOG.md
- autofaiss/version.py
* Fix issue where creating forced memory-mapped indices with faiss-cpu>1.7.2 was failing (#164)
* Support python 3.10 in CI (#165)
* Loosen pyarrow version constraints
> Release 2.15.7

- autofaiss/indices/index_utils.py
A different approach to fix https://github.com/criteo/autofaiss/issues/143.
Instead of keeping the temporary file, we can just close it. Apparently, the problem is that Windows does not allow repeatedly opening files. I believe that this solution should be preferred over https://github.com/criteo/autofaiss/pull/144, which turns the temporary file into a non-temporary one.
> Improve windows compatibility

- autofaiss/indices/distributed.py
In order to avoid failures upon concurrent executions.
Only used when `distributed = "pyspark"`
> Add some random to temporary small indices path
